apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: test
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PASSWORD
              value: test
            - name: POSTGRES_USER
              value: test
          image: pg:v0.2
          name: local-pg
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-cm0
      hostname: postgres
      restartPolicy: Always
      volumes:
        - configMap:
            name: db-cm0
          name: db-cm0
