apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out kompose
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: webapp
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webapp
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out kompose
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: webapp
    spec:
      containers:
        - args:
            - python
            - /root/app/tcf/main.py
          image: tcf:v0.2
          name: tcf-app
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
